### ISSUE TITLE
Is this project related to OpenJScad?

### ISSUE THREAD

**Issue by serapath** [OpenWebCAD/node-occ#28]
Its probably a trivial question, but it's my first time to "venture" into 3D modelling related stuff and because I usually do JavaScript, I'd like to have some synergy effects where possible.

I found blender to have a plugin to interface with OpenJScad, but now also stumbled upon node-occ.
I'm really new and lack all the fundamental basics that i should probably know about, hence my probably trivial question.

What is the background of this project? Why does it exist? How does it compare to alternatives :-)
If you could point me at some learning resources or give me a small overview so I have some orientation, that would be neat ;-)

**Comment by ceremcem** [comment]
I want to note that the difference I've spotted is that if a webapp uses a distant server to process scripts, then there is only a tiny amount of data should be sent/received back and forth. However, if user wants to implement some visual stuff to modify the code (such as dragging objects by mouse) there would be an extensive amount of data transmission needed which OpenJScad shouldn't need by definition. This, I think, the key difference between OpenJScad and node-occ.
