### ISSUE TITLE
create a Mesh from scratch

### ISSUE THREAD

**Issue by luren0** [OpenWebCAD/node-occ#30]
Hello. Is there a way to create a mesh from a list of vertices and faces so it can be used as a shape for boolean operations?

Looks like new occ.Mesh() is available but I don't see how too actually build the mesh.

**Comment by erossignon** [comment]
Yes, it should be possible to do so by creating shell or solids from basic primitive.
You need to create  vertices , then wires with vertex and then faces from wires and finally solids from faces.
