### ISSUE TITLE
not able to do npm install on node occ - getting following error

### ISSUE THREAD

**Issue by pranav-pkasthana** [OpenWebCAD/node-occ#31]
node-pre-gyp ERR! Tried to download(404): https://github.com/openwebcad/node-occ/releases/download/0.2.2/occ-v0.2.2-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-occ@0.2.2 and node@6.11.5 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chinky\\Desktop\\nGitRepo\\node-occ\\projects\\node-occ\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\chinky\\Desktop\\nGitRepo\\node-occ\\projects\\node-occ\\lib\\binding\\occ.node" "--module_name=occ" "--module_path=C:\\Users\\chinky\\Desktop\\nGitRepo\\node-occ\\projects\\node-occ\\lib\\binding"
gyp ERR! cwd C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\lib\binding\occ.node --module_name=occ --module_path=C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chinky\\Desktop\\nGitRepo\\node-occ\\projects\\node-occ\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ
node-pre-gyp ERR! node -v v6.11.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\lib\binding\occ.node --module_name=occ --module_path=C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\lib\binding' (1)

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-occ@0.2.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-occ@0.2.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-occ package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-occ
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-occ
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\chinky\Desktop\nGitRepo\node-occ\projects\node-occ\npm-debug.log

**Comment by kuwiano** [comment]
Same issue here. Solved it by using this version in my package.json:

```
"node-occ": "^0.2.0"
```

**Comment by erossignon** [comment]
Please use a more recent version of node ( 6 or 8 )
