### ISSUE TITLE
Is this library is ever working ?

### ISSUE THREAD

**Issue by semixor** [OpenWebCAD/node-occ#33]
Hi.
Wanted to test this library (Ubuntu) but I can't install it, the tutorial seems to be corrupted, there is no prepare_build.sh file at all.

Thank you.

**Comment by Zhouyiduo** [comment]
![default](https://user-images.githubusercontent.com/29697734/38191748-6fa9bc74-3659-11e8-8803-68c9b97e368c.png)

**Comment by Zhouyiduo** [comment]
npm install node-occ is Error.The down path is wrong?

**Comment by ceremcem** [comment]
@semixor See https://github.com/OpenWebCAD/node-occ/issues/34#issuecomment-427680642
