### ISSUE TITLE
I not compile 

### ISSUE THREAD

**Issue by Zhouyiduo** [OpenWebCAD/node-occ#34]
on ubuntu
# installing nodejs and gyp utility to build extensions
sudo apt-get install nodejs npm
sudo npm install node-pre-gyp -g
sudo npm install mocha -g

#installing cmake
sudo apt-get install cmake cmake-curses-gui g++ build-essential

# ------------------------------------
git clone --recursive https://github.com/erossignon/node-occ.git
cd node-occ
sh prepare_build.sh
npm install
node-pre-gyp configure
node-pre-gyp build
mocha

down last vision,  prepare_build.sh 's file is not exist.   The result that sh prepare_node.sh is 
![2018-04-09 20_18_15-ubuntu64 - oracle vm virtualbox](https://user-images.githubusercontent.com/29697734/38497324-551c6570-3c33-11e8-802e-0122c43c8720.png)

**Comment by ceremcem** [comment]
@Zhouyiduo You may manually follow https://github.com/OpenWebCAD/node-occ/pull/35
