### ISSUE TITLE
There were something wrong with the Sample project

### ISSUE THREAD

**Issue by wuxiaod1987** [OpenWebCAD/node-occ#39]
1 There is not sample folder in node-occ.
2 So, I clone node-occ-sample into node-occ.
3 when I run 'npm install' in 'node-occ-sample' folder, there are 2 404 fatals, node can not find the right version node-occ files.
4 So, I download 'occ-v0.2.0-node-v57-win32-x64.tar.gz'  manually, then copy dll files into sample folder then npm install can finish.
5 But I cannot find app.js file in 'node-occ-sample' folder.
6 So I try to run client.js, but the server is not start.....I don't know how to go on...

**Comment by ceremcem** [comment]
Here is the working state of the sample project (with some trivial UI malfunction, though): https://aktos.io/webcad/

1. Install node-occ appropriately (see `make test` succeeds)
2. Go to node-occ-sample directory and type `npm start`. 

I'm using Linux, so it's not easy for me to supply help for Windows. Anyway, you are doing it wrong in step 5 and step 6, I think. Try running the server by `npm start`.

**Comment by wuxiaod1987** [comment]
Thank you for you reply, it is very great job you have done.
I tried for 2Days, now I can run the 'node-occ-sample' by a node server, but it cannot create geometries. There might still be something wrong of me, I will try.
For purpose of creating a CAE platform, I am trying to trans it into asp.net core, but it is a far way to go.

**Comment by ceremcem** [comment]
Please consider closing this issue if it is resolved.
