### ISSUE TITLE
Some errord happend when build node-occ

### ISSUE THREAD

**Issue by wuxiaod1987** [OpenWebCAD/node-occ#40]
I build on Ubuntu 18.04, when I execute command 'node-gyp build', there comes follow errs:
gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "configure"
gyp ERR! cwd /home/sheldonwu/WXD/node-occ
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
I try I for some times but it cannot be fixed, then if I run 'node-gyp build' there still errs.

**Comment by ceremcem** [comment]
Try this: 

```
# installing nodejs and gyp utility to build extensions
sudo apt-get install nodejs npm
sudo npm install node-pre-gyp -g
sudo npm install mocha -g

#installing cmake
sudo apt-get install cmake cmake-curses-gui g++ build-essential libtbb2

# ------------------------------------
git clone --recursive https://github.com/erossignon/node-occ.git
cd node-occ
./build.sh                     
make test
```
