### ISSUE TITLE
Does not working in both linux and windows. Always pulling error while "npm install" stage

### ISSUE THREAD

**Issue by shibinmohankv** [OpenWebCAD/node-occ#42]
node-occ@0.3.0 preinstall C:\projects1\node-occ\node-occ
> node build.js

> node-occ@0.3.0 install C:\projects1\node-occ\node-occ
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for node-occ@0.3.0 and node@6.17.1 (node-v48 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error EEXIST: file already exists, mkdir 'C:\projects1\node-occ\node-occ\lib\binding'
Warning: Missing input files:
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKOffset.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKG3d.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKGeomAlgo.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKBool.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKSTEP209.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKBRep.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKSTEPAttr.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKPrim.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKShHealing.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKBO.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKMesh.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKSTEPBase.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKTopAlgo.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKSTEP.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKMath.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKXSBase.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKG2d.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKGeomBase.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKFillet.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKernel.dll
C:\projects1\node-occ\node-occ\build\..\occt-7.2.0\win64\vc14\bin\TKSTL.dll
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  all.cc
  win_delay_load_hook.cc
c:\projects1\node-occ\node-occ\src\occ.h(4): fatal error C1083: Cannot open
include file: 'Standard_Version.hxx': No such file or directory (compiling s
ource file ..\src\all.cc) [C:\projects1\node-occ\node-occ\build\occ.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\shibin.m\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:190:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\shibin.m\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\projects1\\node-occ\\node-occ\\lib\\binding\\occ.node" "--module_name=occ" "--module_path=C:\\projects1\\node-occ\\node-occ\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v48"
gyp ERR! cwd C:\projects1\node-occ\node-occ
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\shibin.m\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects1\node-occ\node-occ\lib\binding\occ.node --module_name=occ --module_path=C:\projects1\node-occ\node-occ\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v48' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\projects1\node-occ\node-occ\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:920:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects1\\node-occ\\node-occ\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\projects1\node-occ\node-occ
node-pre-gyp ERR! node -v v6.17.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\shibin.m\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\projects1\node-occ\node-occ\lib\binding\occ.node --module_name=occ --module_path=C:\projects1\node-occ\node-occ\lib\binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v48' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-occ@0.3.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-occ@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shibin.m\AppData\Roaming\npm-cache\_logs\2019-07-19T12_02_40_073Z-debug.log
![error2](https://user-images.githubusercontent.com/53084830/61533826-c7b8f080-a9e2-11e9-84bb-225b3ccb64a6.PNG)
![error3](https://user-images.githubusercontent.com/53084830/61533836-cb4c7780-a9e2-11e9-84c7-d947effac96b.PNG)

Always pulling these errors when using "npm install"

**Comment by ceremcem** [comment]
Please try [this procedure](https://github.com/OpenWebCAD/node-occ/issues/40#issuecomment-504672403) for Linux.

**Comment by erossignon** [comment]
the build procedure is in build.sh
